apiVersion: v1
kind: Secret
metadata:
  name: fitness-analytics-postgres-secrets
  namespace: fitness-analytics-namespace
type: Opaque
stringData:
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: admin123
  POSTGRES_DB: postgresdb
