apiVersion: v1
kind: Secret
metadata:
  name: fitness-analytics-postgres-secrets
  namespace: fitness-analytics-namespace
type: Opaque
stringData:
  POSTGRES_USER: <Postgres User>
  POSTGRES_PASSWORD: <postgres password>
  POSTGRES_DB: <postgresdatabase name>
