apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: fitness-analytics-spark-application
  namespace: fitness-analytics-namespace
spec:
  type: Python
  mode: cluster

  image: pindio58/fitness-spark-image:5.3
  imagePullPolicy: IfNotPresent

  mainApplicationFile: local:///opt/spark/jobs/sample.py
  sparkVersion: "4.0.0"

  sparkConf:
    "spark.driver.extraJavaOptions": "--enable-native-access=ALL-UNNAMED"
    "spark.executor.extraJavaOptions": "--enable-native-access=ALL-UNNAMED"
    "spark.kubernetes.driver.deleteOnTermination": "true"
    "spark.kubernetes.executor.deleteOnTermination": "true"
    "spark.hadoop.fs.s3a.aws.credentials.provider": "org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider"
    "spark.hadoop.fs.s3a.endpoint": "http://fitness-analytics-minio-service:9000"
    "spark.hadoop.fs.s3a.path.style.access": "true"
    "spark.hadoop.fs.s3a.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"
    "spark.hadoop.fs.s3a.connection.ssl.enabled": "false"
    "spark.hadoop.fs.s3a.access.key": "postgresadmin"
    "spark.hadoop.fs.s3a.secret.key": "admin123"

  # new
    # Mount ConfigMap with Python scripts
  volumes:
    - name: spark-jobs
      configMap:
        name: spark-jobs  # create this ConfigMap with your Python file

  driver:
    cores: 1
    memory: "1g"
    serviceAccount: spark
    envFrom:
      - configMapRef:
          name: fitness-analytics-minio-configmap

    volumeMounts:
      - name: spark-jobs
        mountPath: /opt/spark/jobs

  executor:
    cores: 1
    instances: 1
    memory: "1g"
    serviceAccount: spark
    envFrom:
      - configMapRef:
          name: fitness-analytics-minio-configmap

    volumeMounts:
      - name: spark-jobs
        mountPath: /opt/spark/jobs

  restartPolicy:
    type: Never


  
