postgresql:
  enabled: true
  image:
    registry: docker.io
    repository: postgres
    tag: 15.15

images:
  airflow:
    # registry: docker.io
    pullPolicy: IfNotPresent
    repository: pindio58/fitness-airflow-image
    tag: "6.0"

dags:
  gitSync:
    enabled: true
    repo: https://github.com/pindio58/fitness-analytics-v3.git
    rev: HEAD
    branch: automatic_connections
    containerLifecycleHooks: {}
    containerName: git-sync
    depth: 1
    subPath: airflow/dags
    wait: 0

  persistence:
    enabled: false

extraEnvFrom: |-
  - secretRef: 
      name: fitness-analytics-strava-secret
  - configMapRef:
      name: fitness-analytics-strava-configmap

webserver:
  env:
    - name: BUCKET_NAME
      valueFrom:
        configMapKeyRef:
          name: fitness-analytics-minio-configmap
          key: BUCKET_NAME

    - name: MINIO_ENDPOINT
      valueFrom:
        configMapKeyRef:
          name: fitness-analytics-minio-configmap
          key: MINIO_ENDPOINT

    - name: AIRFLOW_CONN_POSTGRES_CONN
      valueFrom:
        secretKeyRef:
          name: fitness-analytics-airflow-secret
          key: postgres_conn

    - name: AIRFLOW_CONN_MINIO_DEFAULT
      valueFrom:
        secretKeyRef:
          name: fitness-analytics-airflow-secret
          key: minio_default

    - name: AIRFLOW_CONN_SPARK_KUBERNETES_DEFAULT
      valueFrom:
        secretKeyRef:
          name: fitness-analytics-airflow-secret
          key: spark_kubernetes_default
  # envFrom:
  #   - secretRef:
  #       name: fitness-analytics-strava-secret
  #   - configMapRef:
  #       name: fitness-analytics-strava-configmap

scheduler:
  env:
    - name: BUCKET_NAME
      valueFrom:
        configMapKeyRef:
          name: fitness-analytics-minio-configmap
          key: BUCKET_NAME

    - name: MINIO_ENDPOINT
      valueFrom:
        configMapKeyRef:
          name: fitness-analytics-minio-configmap
          key: MINIO_ENDPOINT

    - name: AIRFLOW_CONN_POSTGRES_CONN
      valueFrom:
        secretKeyRef:
          name: fitness-analytics-airflow-secret
          key: postgres_conn

    - name: AIRFLOW_CONN_MINIO_DEFAULT
      valueFrom:
        secretKeyRef:
          name: fitness-analytics-airflow-secret
          key: minio_default

    - name: AIRFLOW_CONN_SPARK_KUBERNETES_DEFAULT
      valueFrom:
        secretKeyRef:
          name: fitness-analytics-airflow-secret
          key: spark_kubernetes_default

  # envFrom:
  #   - secretRef:
  #       name: fitness-analytics-strava-secret
  #   - configMapRef:
  #       name: fitness-analytics-strava-configmap

apiServer:
  env:
    - name: BUCKET_NAME
      valueFrom:
        configMapKeyRef:
          name: fitness-analytics-minio-configmap
          key: BUCKET_NAME

    - name: MINIO_ENDPOINT
      valueFrom:
        configMapKeyRef:
          name: fitness-analytics-minio-configmap
          key: MINIO_ENDPOINT

    - name: AIRFLOW_CONN_POSTGRES_CONN
      valueFrom:
        secretKeyRef:
          name: fitness-analytics-airflow-secret
          key: postgres_conn

    - name: AIRFLOW_CONN_MINIO_DEFAULT
      valueFrom:
        secretKeyRef:
          name: fitness-analytics-airflow-secret
          key: minio_default

    - name: AIRFLOW_CONN_SPARK_KUBERNETES_DEFAULT
      valueFrom:
        secretKeyRef:
          name: fitness-analytics-airflow-secret
          key: spark_kubernetes_default
  # envFrom:
  #   - secretRef:
  #       name: fitness-analytics-strava-secret
  #   - configMapRef:
  #       name: fitness-analytics-strava-configmap

workers:
  env:
    - name: BUCKET_NAME
      valueFrom:
        configMapKeyRef:
          name: fitness-analytics-minio-configmap
          key: BUCKET_NAME

    - name: MINIO_ENDPOINT
      valueFrom:
        configMapKeyRef:
          name: fitness-analytics-minio-configmap
          key: MINIO_ENDPOINT

    - name: AIRFLOW_CONN_POSTGRES_CONN
      valueFrom:
        secretKeyRef:
          name: fitness-analytics-airflow-secret
          key: postgres_conn

    - name: AIRFLOW_CONN_MINIO_DEFAULT
      valueFrom:
        secretKeyRef:
          name: fitness-analytics-airflow-secret
          key: minio_default

    - name: AIRFLOW_CONN_SPARK_KUBERNETES_DEFAULT
      valueFrom:
        secretKeyRef:
          name: fitness-analytics-airflow-secret
          key: spark_kubernetes_default

  # envFrom:
  #   - secretRef:
  #       name: fitness-analytics-strava-secret
  #   - configMapRef:
  #       name: fitness-analytics-strava-configmap

#  for following, please refer https://www.notion.so/Could-not-read-served-logs-Invalid-URL-http-8793-log-dag_id-No-host-supplied-2d5e0b22664f80598880f22e3a0e2474?v=2c2e0b22664f8095acf9000cdc510362&source=copy_link
webserverSecretKeySecretName: fitness-analytics-airflow-secret
# config:
#   core:
#     hostname_callable: airflow.utils.net.get_host_ip_address
#   logging:
#     hostname_callable: airflow.utils.net.get_host_ip_address
#   api:
#     hostname_callable: airflow.utils.net.get_host_ip_address

# https://www.notion.so/rest-db-on-every-Airflow-restart-311e0b22664f80518723fdc146fabd00?source=copy_link
migrateDatabaseJob:
  enabled: true
