apiVersion: v1
kind: Secret
metadata:
  name: fitness-analytics-airflow-secret
  namespace: fitness-analytics-namespace
type: Opaque
stringData:
  webserver-secret-key: "tJLo32YXl8XL3MfQ9OtD67eOLkPhvsSQ7rK6KYGRBQw="
