apiVersion: v1
kind: Secret
metadata:
  name: fitness-analytics-airflow-secret
  namespace: fitness-analytics-namespace
type: Opaque
stringData:
  webserver-secret-key: "QKCcIsCmJa4r2t-MP4UoAUEwQd7FO88FEsDI6w3m7tI="
