apiVersion: v1
kind: Secret
metadata:
  name: fitness-analytics-airflow-secret
  namespace: fitness-analytics-namespace
type: Opaque
stringData:
  webserver-secret-key: "HCwBa7adqDif394AXtdy252Jyj8Cn_v4scyqgkZd-MQ="
