apiVersion: v1
kind: Secret
metadata:
  name: fitness-analytics-airflow-secret-template
  namespace: fitness-analytics-namespace
type: Opaque
stringData:
  webserver-secret-key: "<generate secret key>"
