apiVersion: v1
kind: Secret
metadata:
  name: fitness-analytics-minio-secrets
  namespace: fitness-analytics-namespace
type: Opaque
stringData:
  MINIO_ROOT_USER: <Minio User>
  MINIO_ROOT_PASSWORD: <Minio password>
  NEWUSERNAME: <new user username>
  NEWPASSWORD: <new user password>
