apiVersion: v1
kind: ConfigMap
metadata:
  name: fitness-analytics-minio-configmap
  namespace: fitness-analytics-namespace
data:
  BUCKET_NAME: fitness-analytics
  MINIO_ENDPOINT: http://fitness-analytics-minio-statefulset-0.fitness-analytics-minio-service:9000