apiVersion: v1
kind: Secret
metadata:
  name: fitness-analytics-minio-secrets
  namespace: fitness-analytics-namespace
type: Opaque
stringData:
  MINIO_ROOT_USER: postgresadmin
  MINIO_ROOT_PASSWORD: admin123
  NEWUSERNAME: fitnesslocaluser
  NEWPASSWORD: fitnesslocalpass
