apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: fitness-analytics-namespace
  annotations: 
    kubernetes.io/enforce-mountable-secrets: "true"
secrets:
  - name: fitness-analytics-postgres-secrets
  - name: fitness-analytics-minio-secrets