apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fitness-analytics-statsd-servicemonitor
  namespace: fitness-analytics-namespace
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      # app.kubernetes.io/name: prometheus-statsd-exporter
      component: statsd
      release: airflow
  endpoints:
    - port: statsd-scrape #http
      interval: 15s
      path: /metrics
