apiVersion: v1
kind: Secret
metadata:
  name: fitness-analytics-strava-secret
  namespace: fitness-analytics-namespace
type: Opaque
stringData:
  client_secret: 19d74a3646482ec66e5b211cf98c5e39c1ca6017
  client_id: "207985"
  pg_user: "postgresadmin"
  pg_password: "admin123"
