apiVersion: v1
kind: Secret
metadata:
  name: fitness-analytics-strava-secret
  namespace: fitness-analytics-namespace
type: Opaque
stringData:
  client_secret: <clinet secret>
  client_id: <client id>
  pg_user: <postgres username>
  pg_password: <postgres password>
