apiVersion: v1
kind: ConfigMap
metadata:
  name: fitness-analytics-strava-configmap
  namespace: fitness-analytics-namespace
data:
  url: https://www.strava.com/oauth/token
  athlete_id: <thelete id>
  pg_host: "localhost"
  pg_port: "5433"
  pg_db: "postgresdb"
