apiVersion: v1
kind: PersistentVolume
metadata:
  name: fitness-analytics-minio-pv
  namespace: fitness-analytics-namespace
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: /data/minio