apiVersion: v1
kind: ConfigMap
metadata:
  name: fitness-analytics-spark-configmap
  namespace: fitness-analytics-namespace
data:
    BUCKET_NAME: fitness-analytics
    MINIO_ENDPOINT: http://fitness-analytics-minio-statefulset-0.fitness-analytics-minio-service:9000
    APP_NAME: fitness-analytics
    POSTGRES_DB: fitness
    POSTGRES_HOST: fitness-analytics-postgres-service
    POSTGRES_PORT: "5432"
