apiVersion: v1
kind: Secret
metadata:
  name: fitness-analytics-spark-secret
  namespace: fitness-analytics-namespace
type: Opaque
stringData:
    MINIO_ROOT_USER: <Minio user name>
    MINIO_ROOT_PASSWORD: <Minio password>
    POSTGRES_USER: <postgres username>
    POSTGRES_PASSWORD: <postgres password>
