apiVersion: v1
kind: Secret
metadata:
  name: fitness-analytics-spark-secret
  namespace: fitness-analytics-namespace
type: Opaque
stringData:
    MINIO_ROOT_USER: postgresadmin
    MINIO_ROOT_PASSWORD: admin123
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
