config:
  datasource:
    host: "fitness-analytics-postgres-service"
    port: "5432"
    database: "postgresdb"
    userSecret:
      name: fitness-analytics-postgres-secrets
      key: POSTGRES_USER

    passwordSecret:
      name: fitness-analytics-postgres-secrets
      key: POSTGRES_PASSWORD

serviceMonitor:
  enabled: true
  apiVersion: "monitoring.coreos.com/v1"
  namespace: fitness-analytics-namespace
  interval: 10s
  labels:
    release: prometheus
