apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fitness-analytics-postgres-statefulset
  namespace: fitness-analytics-namespace
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: fitness-analytics-postgres-service
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: fitness-analytics-postgres-secrets
                key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: fitness-analytics-postgres-secrets
                key: POSTGRES_USER
                optional: false
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: fitness-analytics-postgres-secrets
                key: POSTGRES_PASSWORD
                optional: false
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
